### ISSUE TITLE
EventCategory Error in Admin Panel 

### ISSUE THREAD

**Issue by sreno77** [bitlabstudio/django-calendarium#65]
When I go to the EventCategory page in the admin panel I get 'TypeError at /admin/calendarium/eventcategory/' and the page won't load. I'm on Python 3.8.10 and Django 3.2

**Comment by Tyrdall** [comment]
@sreno77 This project is not working with Django 3.2 https://github.com/bitlabstudio/django-calendarium#compatibility

Feel free to come up with a merge request.
